branches:
  only:
    - master

before_install: npm install -g grunt-cli
install: npm install
language: node_js
node_js:
  - "0.10"

env:
  global:
  - GH_REF: github.com/Syonet/bootstrap-legacy.git

  # GH_TOKEN
  - secure: du4M6/6HkzSqxWcExdbVilEsPUMa66sjyagY+jtRaX7v/1DS1STs8NIZqzKKRXRbKxVT4coNyrepBjUZtk7a+lv2ca+mCZiwWzvtjGnMcINUnDv16ZtSJeQ+5/X1/Q+FETSrlhsiuW1p+/bjEoRsmHuzHER68d48LqyMd6b9wJY=

after_success:
  - git push --force --quiet "https://${GH_TOKEN}:x-oauth-basic@${GH_REF}" master:gh-pages > /dev/null 2>&1